version: "3"

services:
  web:
    build: .
      dockerfile: docker/dev.Dockerfile
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.example
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=fastdb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

