version: "3"

services:
  web:
    build: 
      dockerfile: docker/dev.Dockerfile
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.example
    depends_on:
      - mongodb
      - minio

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=fastdb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  minio:
    container_name: minio
    image: minio/minio
    command: server --console-address :9090 /data
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      - MINIO_ROOT_USER=username
      - MINIO_ROOT_PASSWORD=password
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_SECURE=False
      - MINIO_BUCKET_NAME=minio-bucket
    volumes:
      - ./minio-data:/data
